"""create football knowledge base"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
revision: str="0001"
down_revision: Union[str,None]=None
branch_labels: Union[str,Sequence[str],None]=None
depends_on: Union[str,Sequence[str],None]=None
def upgrade()->None:
    op.create_table("countries",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("name",sa.String(100),nullable=False,unique=True),sa.Column("code",sa.String(10),nullable=True,unique=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("stadiums",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("name",sa.String(150),nullable=False),sa.Column("city",sa.String(100),nullable=True),sa.Column("capacity",sa.Integer(),nullable=True),sa.Column("country_id",sa.Integer(),sa.ForeignKey("countries.id"),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("competitions",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("api_id",sa.Integer(),nullable=True,unique=True),sa.Column("name",sa.String(150),nullable=False),sa.Column("competition_type",sa.String(50),nullable=False),sa.Column("country_id",sa.Integer(),sa.ForeignKey("countries.id"),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("seasons",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("competition_id",sa.Integer(),sa.ForeignKey("competitions.id"),nullable=False),sa.Column("name",sa.String(30),nullable=False),sa.Column("start_date",sa.Date(),nullable=True),sa.Column("end_date",sa.Date(),nullable=True),sa.Column("is_current",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("competition_id","name",name="uq_season_competition_name"))
    op.create_table("managers",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("api_id",sa.Integer(),nullable=True,unique=True),sa.Column("name",sa.String(150),nullable=False),sa.Column("nationality",sa.String(100),nullable=True),sa.Column("date_of_birth",sa.Date(),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("referees",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("api_id",sa.Integer(),nullable=True,unique=True),sa.Column("name",sa.String(150),nullable=False),sa.Column("nationality",sa.String(100),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("teams",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("api_id",sa.Integer(),nullable=True,unique=True),sa.Column("name",sa.String(150),nullable=False),sa.Column("short_name",sa.String(50),nullable=True),sa.Column("founded_year",sa.Integer(),nullable=True),sa.Column("country_id",sa.Integer(),sa.ForeignKey("countries.id"),nullable=True),sa.Column("stadium_id",sa.Integer(),sa.ForeignKey("stadiums.id"),nullable=True),sa.Column("current_manager_id",sa.Integer(),sa.ForeignKey("managers.id"),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("fixtures",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("api_id",sa.Integer(),nullable=True,unique=True),sa.Column("season_id",sa.Integer(),sa.ForeignKey("seasons.id"),nullable=False),sa.Column("home_team_id",sa.Integer(),sa.ForeignKey("teams.id"),nullable=False),sa.Column("away_team_id",sa.Integer(),sa.ForeignKey("teams.id"),nullable=False),sa.Column("referee_id",sa.Integer(),sa.ForeignKey("referees.id"),nullable=True),sa.Column("stadium_id",sa.Integer(),sa.ForeignKey("stadiums.id"),nullable=True),sa.Column("kickoff_at",sa.DateTime(timezone=True),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("home_score",sa.Integer(),nullable=True),sa.Column("away_score",sa.Integer(),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("transfers",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("player_name",sa.String(150),nullable=False),sa.Column("from_team_id",sa.Integer(),sa.ForeignKey("teams.id"),nullable=True),sa.Column("to_team_id",sa.Integer(),sa.ForeignKey("teams.id"),nullable=True),sa.Column("transfer_date",sa.Date(),nullable=False),sa.Column("transfer_window",sa.String(30),nullable=False),sa.Column("fee_amount",sa.Numeric(14,2),nullable=True),sa.Column("fee_currency",sa.String(3),nullable=True),sa.Column("transfer_type",sa.String(30),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
def downgrade()->None:
    for table in ["transfers","fixtures","teams","referees","managers","seasons","competitions","stadiums","countries"]: op.drop_table(table)
